<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/images/SN_web_lightmode.png" width="300" alt="cognitiveclass.ai logo">
</center>

<h1 align=center><font size = 5>Assignment: Notebook for Peer Assignment</font></h1>

# Introduction

Using this Python notebook you will:

1.  Understand three Chicago datasets
2.  Load the three datasets into three tables in a SQLIte database
3.  Execute SQL queries to answer assignment questions

## Understand the datasets

To complete the assignment problems in this notebook you will be using three datasets that are available on the city of Chicago's Data Portal:

1.  <a href="https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Socioeconomic Indicators in Chicago</a>
2.  <a href="https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Chicago Public Schools</a>
3.  <a href="https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Chicago Crime Data</a>

### 1. Socioeconomic Indicators in Chicago

This dataset contains a selection of six socioeconomic indicators of public health significance and a “hardship index,” for each Chicago community area, for the years 2008 – 2012.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:
[https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2](https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### 2. Chicago Public Schools

This dataset shows all school level performance data used to create CPS School Report Cards for the 2011-2012 school year. This dataset is provided by the city of Chicago's Data Portal.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:
[https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t](https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### 3. Chicago Crime Data

This dataset reflects reported incidents of crime (with the exception of murders where data exists for each victim) that occurred in the City of Chicago from 2001 to present, minus the most recent seven days.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:
[https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2](https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### Download the datasets

This assignment requires you to have these three tables populated with a subset of the whole datasets.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the links below to download and save the datasets (.CSV files):

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01" target="_blank">Chicago Census Data</a>

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01" target="_blank">Chicago Public Schools</a>

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCrimeData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01" target="_blank">Chicago Crime Data</a>

**NOTE:** Ensure you have downloaded the datasets using the links above instead of directly from the Chicago Data Portal. The versions linked here are subsets of the original datasets and have some of the column names modified to be more database friendly which will make it easier to complete this assignment.

### Store the datasets in database tables

To analyze the data using SQL, it first needs to be loaded into SQLite DB.
We will create three tables in as under:

1.  **CENSUS_DATA**
2.  **CHICAGO_PUBLIC_SCHOOLS**
3.  **CHICAGO_CRIME_DATA**

Let us now load the ipython-sql  extension and establish a connection with the database

* Here you will be loading the csv files into the pandas Dataframe and then loading the data into the above mentioned sqlite tables.

* Next you will be connecting to the sqlite database  **FinalDB**.

Refer to the previous lab for hints .

<a href ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-4-Analyzing_SQLite.ipynb">Hands-on Lab: Analyzing a real World Data Set</a>

In [10]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [11]:
import csv, sqlite3

con = sqlite3.connect("FinalDB.db")
cur = con.cursor()

In [12]:
!pip install -q pandas==1.1.5
%sql sqlite:///FinalDB.db

'Connected: @FinalDB.db'

In [13]:
import pandas
df = pandas.read_csv('ChicagoPublicSchools.csv')
df.to_sql("CHICAGO_PUBLIC_SCHOOLS", con, if_exists='replace', index=False,method="multi")
import pandas
df = pandas.read_csv('ChicagoCrimeData.csv')
df.to_sql("CHICAGO_CRIME_DATA", con, if_exists='replace', index=False,method="multi")
import pandas
df = pandas.read_csv('ChicagoCensusData.csv')
df.to_sql("CENSUS_DATA", con, if_exists='replace', index=False,method="multi")

## Problems

Now write and execute SQL queries to solve assignment problems

### Problem 1

##### Find the total number of crimes recorded in the CRIME table.

In [15]:
%sql select distinct count(CASE_NUMBER) from CHICAGO_CRIME_DATA

 * sqlite:///FinalDB.db
Done.

[(533,)]

### Problem 2

##### List community areas with per capita income less than 11000.

In [18]:
%sql select COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME from CENSUS_DATA where PER_CAPITA_INCOME<11000;

 * sqlite:///FinalDB.db
Done.

[(26.0, 'West Garfield Park'),
 (30.0, 'South Lawndale'),
 (37.0, 'Fuller Park'),
 (54.0, 'Riverdale')]

### Problem 3

##### List all case numbers for crimes  involving minors?(children are not considered minors for the purposes of crime analysis)

In [28]:
%sql select CASE_NUMBER from CHICAGO_CRIME_DATA where YEAR>strftime('%Y', date('now'))-18;

 * sqlite:///FinalDB.db
Done.

[('HT233595',),
 ('HT133522',),
 ('HZ138551',),
 ('HS540106',),
 ('HZ534771',),
 ('HX552797',),
 ('HT180228',),
 ('HV243612',),
 ('HN200365',),
 ('HY396729',),
 ('HR271603',),
 ('HX332132',),
 ('HW303994',),
 ('HS569246',),
 ('HY234744',),
 ('HP320451',),
 ('HN484464',),
 ('JB151690',),
 ('HR582990',),
 ('HR535632',),
 ('HW441620',),
 ('HR583513',),
 ('HX509438',),
 ('HS681158',),
 ('JA272438',),
 ('HM324025',),
 ('HV353560',),
 ('HR261581',),
 ('HM543491',),
 ('HY167451',),
 ('HY377901',),
 ('HX225704',),
 ('HV528008',),
 ('HS532107',),
 ('JA261898',),
 ('JA559176',),
 ('JA412895',),
 ('HY273740',),
 ('HZ224258',),
 ('HV534721',),
 ('JA503725',),
 ('HM803061',),
 ('HN731220',),
 ('HP691879',),
 ('HV537004',),
 ('HR149903',),
 ('HX314361',),
 ('HV345270',),
 ('HS308747',),
 ('HY291329',),
 ('HY412959',),
 ('HX155070',),
 ('HV402967',),
 ('HX332979',),
 ('HX165034',),
 ('HR385117',),
 ('HS230912',),
 ('JA384163',),
 ('HT368471',),
 ('HY202462',),
 ('HX354359',),
 ('HZ146741',),
 ('HX262353',),
 ('HP317516',),
 ('HZ335434',),
 ('HS678732',),
 ('HM392612',),
 ('HR460350',),
 ('HM117889',),
 ('HR576816',),
 ('HZ372381',),
 ('HZ556726',),
 ('HN421595',),
 ('HS451246',),
 ('HT651635',),
 ('HZ432273',),
 ('HP746347',),
 ('HN772519',),
 ('HZ309936',),
 ('HY368284',),
 ('HT375934',),
 ('JA188596',),
 ('HV395700',),
 ('HT390647',),
 ('JA490957',),
 ('HM556695',),
 ('HX455839',),
 ('HR703960',),
 ('HV445580',),
 ('HP579910',),
 ('HP714065',),
 ('HP716225',),
 ('HW481295',),
 ('HS568476',),
 ('JB213238',),
 ('HS475732',),
 ('HS595785',),
 ('HR408597',),
 ('HT542713',),
 ('HW213573',),
 ('HM217017',),
 ('HY189363',),
 ('HS498285',),
 ('HN224900',),
 ('HR387668',),
 ('HR136920',),
 ('HT457930',),
 ('HP121474',),
 ('HP558812',),
 ('HY192694',),
 ('HN472326',),
 ('JA460432',),
 ('HX239866',),
 ('HM378171',),
 ('HW182288',),
 ('HZ295843',),
 ('HM673431',),
 ('HP352546',),
 ('HR286405',),
 ('HR195987',),
 ('HW261668',),
 ('JA496716',),
 ('JA344492',),
 ('HZ334220',),
 ('HR217367',),
 ('HV268964',),
 ('JA483294',),
 ('HT169840',),
 ('HT621306',),
 ('HS269736',),
 ('HY267896',),
 ('HN568531',),
 ('HT112422',),
 ('HV479133',),
 ('HV592346',),
 ('HZ376709',),
 ('HV573337',),
 ('HR674429',),
 ('HM200888',),
 ('HX467661',),
 ('HX448587',),
 ('HS200939',),
 ('HN335611',),
 ('HZ535494',),
 ('HX154767',),
 ('HM337445',),
 ('HM244120',),
 ('HR342598',),
 ('HW449676',),
 ('HS589302',),
 ('HX145326',),
 ('HN553354',),
 ('HN784049',),
 ('HM303461',),
 ('HM535632',),
 ('HT353855',),
 ('HR125162',),
 ('HN280980',),
 ('JA560123',),
 ('HY405637',),
 ('HP689703',),
 ('HR345366',),
 ('HZ242802',),
 ('HM661326',),
 ('HV366181',),
 ('HR308948',),
 ('HV328581',),
 ('HV267193',),
 ('HS498920',),
 ('HY365876',),
 ('HS305355',),
 ('HN778969',),
 ('HV185969',),
 ('HW555338',),
 ('HV268708',),
 ('HW160463',),
 ('HN355411',),
 ('HV457847',),
 ('HW566855',),
 ('HR281750',),
 ('HX112183',),
 ('HR597126',),
 ('HN558484',),
 ('HR505781',),
 ('HN522324',),
 ('HN647052',),
 ('HT323138',),
 ('HW562748',),
 ('HN719188',),
 ('HT237921',),
 ('HY215032',),
 ('HM762800',),
 ('HN370211',),
 ('HR195962',),
 ('HM284854',),
 ('HR447925',),
 ('HM590293',),
 ('HP513177',),
 ('HN448271',),
 ('HN422493',),
 ('HP263901',),
 ('HT535175',),
 ('JA110097',),
 ('HM360756',),
 ('HN275969',),
 ('HZ544441',),
 ('HS164946',),
 ('HR399710',),
 ('HP243837',),
 ('HP157774',),
 ('HP340132',),
 ('JA246453',),
 ('HN407116',),
 ('JA107722',),
 ('HY204891',),
 ('HZ228967',),
 ('HY385205',),
 ('JA349450',),
 ('HR185873',),
 ('JA470839',),
 ('HY182950',),
 ('HR668156',),
 ('HZ234518',),
 ('HW569852',),
 ('HS314108',),
 ('HN182437',),
 ('HW493063',),
 ('HZ322965',),
 ('HW415978',),
 ('HM535930',),
 ('HZ242203',),
 ('HN213069',),
 ('JA269772',),
 ('HM507529',),
 ('HP258815',),
 ('HS479338',),
 ('HZ403432',),
 ('HV462975',),
 ('HW414519',),
 ('HT315369',),
 ('HT540548',),
 ('HX398190',),
 ('HR206683',),
 ('JA462321',),
 ('HV233824',),
 ('HR307075',),
 ('HZ134318',),
 ('HM437597',),
 ('HW233866',),
 ('HW274134',),
 ('HW526270',),
 ('HP325677',),
 ('HN246122',),
 ('HT434553',),
 ('HR696852',),
 ('HT202584',),
 ('HT251336',),
 ('HV575905',),
 ('HR489129',),
 ('HT427568',),
 ('HR539548',),
 ('HS426544',),
 ('HT556032',),
 ('JA216127',),
 ('HW350078',),
 ('HR308245',),
 ('HY455377',),
 ('HP747058',),
 ('HN645348',),
 ('HS230740',),
 ('HV593288',),
 ('HM757133',),
 ('HV356669',),
 ('HX207970',),
 ('HM733422',),
 ('HX301095',),
 ('HY163644',),
 ('HR140766',),
 ('HN543219',),
 ('HZ463811',),
 ('HN702776',),
 ('HR607189',),
 ('HN519755',),
 ('JA394755',),
 ('HY518743',),
 ('JA550741',),
 ('HZ523997',),
 ('HY455698',),
 ('HT404945',),
 ('HM422467',),
 ('JA192460',),
 ('HS330202',),
 ('HP661088',),
 ('HN136243',),
 ('HV213648',),
 ('HV514287',),
 ('JA133264',),
 ('JA557966',),
 ('HV548880',),
 ('HR480844',),
 ('HW568748',),
 ('JA393243',),
 ('HR585012',),
 ('JA455629',),
 ('HV369974',),
 ('HN637742',),
 ('HW557360',),
 ('HM802052',),
 ('HR190881',),
 ('HN595319',),
 ('HM590468',),
 ('HV463112',),
 ('HS100098',),
 ('HW576249',),
 ('HM576559',),
 ('HV356389',),
 ('HX203242',),
 ('HN567387',),
 ('HR391350',),
 ('HM768251',),
 ('HT394616',),
 ('HR314298',),
 ('HT404326',),
 ('HY259084',),
 ('HP265256',),
 ('HR392537',),
 ('HX343113',),
 ('HM195342',),
 ('HW519443',),
 ('JA359626',),
 ('HN144152',),
 ('HN544458',),
 ('HW238778',),
 ('JB155558',),
 ('HY458571',),
 ('HZ378869',),
 ('HZ378355',),
 ('HX258445',),
 ('HZ192829',),
 ('HZ133234',),
 ('JA143710',)]

### Problem 4

##### List all kidnapping crimes involving a child?

In [31]:
%sql select PRIMARY_TYPE,DESCRIPTION from CHICAGO_CRIME_DATA where PRIMARY_TYPE = "KIDNAPPING";

 * sqlite:///FinalDB.db
Done.

[('KIDNAPPING', 'CHILD ABDUCTION/STRANGER')]

### Problem 5

##### What kinds of crimes were recorded at schools?

In [34]:
%sql select distinct c1.PRIMARY_TYPE from CHICAGO_CRIME_DATA c1,CHICAGO_PUBLIC_SCHOOLS c2 where c1.COMMUNITY_AREA_NUMBER = c2.COMMUNITY_AREA_NUMBER;

 * sqlite:///FinalDB.db
Done.

[('THEFT',),
 ('BATTERY',),
 ('CRIMINAL DAMAGE',),
 ('NARCOTICS',),
 ('OTHER OFFENSE',),
 ('ASSAULT',),
 ('BURGLARY',),
 ('MOTOR VEHICLE THEFT',),
 ('DECEPTIVE PRACTICE',),
 ('ROBBERY',),
 ('CRIMINAL TRESPASS',),
 ('PROSTITUTION',),
 ('WEAPONS VIOLATION',),
 ('PUBLIC PEACE VIOLATION',),
 ('OFFENSE INVOLVING CHILDREN',),
 ('CRIM SEXUAL ASSAULT',),
 ('SEX OFFENSE',),
 ('INTERFERENCE WITH PUBLIC OFFICER',),
 ('GAMBLING',),
 ('LIQUOR LAW VIOLATION',),
 ('ARSON',),
 ('HOMICIDE',),
 ('KIDNAPPING',),
 ('INTIMIDATION',),
 ('STALKING',),
 ('OBSCENITY',),
 ('CONCEALED CARRY LICENSE VIOLATION',),
 ('PUBLIC INDECENCY',),
 ('NON-CRIMINAL',),
 ('OTHER NARCOTIC VIOLATION',),
 ('HUMAN TRAFFICKING',),
 ('NON - CRIMINAL',),
 ('RITUALISM',),
 ('NON-CRIMINAL (SUBJECT SPECIFIED)',)]

### Problem 6

##### List the average safety score for each type of school.

In [46]:
%sql select avg(SAFETY_SCORE) as average_safety_score from CHICAGO_PUBLIC_SCHOOLS GROUP BY "Elementary, Middle, or High School";

 * sqlite:///FinalDB.db
Done.

[(49.52038369304557,), (49.62352941176471,), (48.0,)]

### Problem 7

##### List 5 community areas with highest % of households below poverty line

In [51]:
%sql select COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME from CENSUS_DATA ORDER BY PERCENT_HOUSEHOLDS_BELOW_POVERTY DESC LIMIT 5;

 * sqlite:///FinalDB.db
Done.

[(54.0, 'Riverdale'),
 (37.0, 'Fuller Park'),
 (68.0, 'Englewood'),
 (29.0, 'North Lawndale'),
 (27.0, 'East Garfield Park')]

### Problem 8

##### Which community area is most crime prone?

In [55]:
%sql SELECT COMMUNITY_AREA_NUMBER,COUNT(*) AS CRIME_COUNT FROM CHICAGO_CRIME_DATA GROUP BY COMMUNITY_AREA_NUMBER ORDER BY CRIME_COUNT DESC LIMIT 1;

 * sqlite:///FinalDB.db
Done.

[(25.0, 43)]

### Problem 9

##### Use a sub-query to find the name of the community area with highest hardship index

In [56]:
%sql select COMMUNITY_AREA_NAME from CENSUS_DATA where HARDSHIP_INDEX = (select max(HARDSHIP_INDEX) from CENSUS_DATA);

 * sqlite:///FinalDB.db
Done.

[('Riverdale',)]

### Problem 10

##### Use a sub-query to determine the Community Area Name with most number of crimes?

In [59]:
%sql select distinct c2.COMMUNITY_AREA_NAME from CHICAGO_CRIME_DATA c1,CENSUS_DATA c2 where c1.COMMUNITY_AREA_NUMBER = (select c1.COMMUNITY_AREA_NUMBER from CHICAGO_CRIME_DATA c1 GROUP BY c1.COMMUNITY_AREA_NUMBER ORDER BY count(*) DESC LIMIT 1);

 * sqlite:///FinalDB.db
Done.

[('Rogers Park',),
 ('West Ridge',),
 ('Uptown',),
 ('Lincoln Square',),
 ('North Center',),
 ('Lake View',),
 ('Lincoln Park',),
 ('Near North Side',),
 ('Edison Park',),
 ('Norwood Park',),
 ('Jefferson Park',),
 ('Forest Glen',),
 ('North Park',),
 ('Albany Park',),
 ('Portage Park',),
 ('Irving Park',),
 ('Dunning',),
 ('Montclaire',),
 ('Belmont Cragin',),
 ('Hermosa',),
 ('Avondale',),
 ('Logan Square',),
 ('Humboldt park',),
 ('West Town',),
 ('Austin',),
 ('West Garfield Park',),
 ('East Garfield Park',),
 ('Near West Side',),
 ('North Lawndale',),
 ('South Lawndale',),
 ('Lower West Side',),
 ('Loop',),
 ('Near South Side',),
 ('Armour Square',),
 ('Douglas',),
 ('Oakland',),
 ('Fuller Park',),
 ('Grand Boulevard',),
 ('Kenwood',),
 ('Washington Park',),
 ('Hyde Park',),
 ('Woodlawn',),
 ('South Shore',),
 ('Chatham',),
 ('Avalon Park',),
 ('South Chicago',),
 ('Burnside',),
 ('Calumet Heights',),
 ('Roseland',),
 ('Pullman',),
 ('South Deering',),
 ('East Side',),
 ('West Pullman',),
 ('Riverdale',),
 ('Hegewisch',),
 ('Garfield Ridge',),
 ('Archer Heights',),
 ('Brighton Park',),
 ('McKinley Park',),
 ('Bridgeport',),
 ('New City',),
 ('West Elsdon',),
 ('Gage Park',),
 ('Clearing',),
 ('West Lawn',),
 ('Chicago Lawn',),
 ('West Englewood',),
 ('Englewood',),
 ('Greater Grand Crossing',),
 ('Ashburn',),
 ('Auburn Gresham',),
 ('Beverly',),
 ('Washington Height',),
 ('Mount Greenwood',),
 ('Morgan Park',),
 ("O'Hare",),
 ('Edgewater',),
 ('CHICAGO',)]

Copyright © 2020 This notebook and its source code are released under the terms of the [MIT License](https://bigdatauniversity.com/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).

## Author(s)

<h4> Hima Vasudevan </h4>
<h4> Rav Ahuja </h4>
<h4> Ramesh Sannreddy </h4>

## Contribtuor(s)

<h4> Malika Singla </h4>

## Change log

| Date       | Version | Changed by        | Change Description                             |
| ---------- | ------- | ----------------- | ---------------------------------------------- |
| 2022-03-04 | 2.5     | Lakshmi Holla     | Changed markdown.                   |
| 2021-05-19 | 2.4     | Lakshmi Holla     | Updated the question                           |
| 2021-04-30 | 2.3     | Malika Singla     | Updated the libraries                          |
| 2021-01-15 | 2.2     | Rav Ahuja         | Removed problem 11 and fixed changelog         |
| 2020-11-25 | 2.1     | Ramesh Sannareddy | Updated the problem statements, and datasets   |
| 2020-09-05 | 2.0     | Malika Singla     | Moved lab to course repo in GitLab             |
| 2018-07-18 | 1.0     | Rav Ahuja         | Several updates including loading instructions |
| 2018-05-04 | 0.1     | Hima Vasudevan    | Created initial version                        |

## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>